# Generated by Django 3.2.4 on 2021-09-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2022)),
                ('description', models.CharField(default='not_current_year', max_length=25)),
            ],
        ),
    ]
