# Generated by Django 3.2.4 on 2021-09-22 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021)),
                ('dimension', models.IntegerField(default=26)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
