# Generated by Django 3.2.4 on 2021-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_leavedimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_str', models.CharField(max_length=25, unique=True)),
                ('day_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leavedimension',
            unique_together={('year', 'user')},
        ),
    ]
