# Generated by Django 3.2.4 on 2021-09-25 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20210924_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFreeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_str', models.CharField(max_length=25, unique=True)),
                ('day_date', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day_str')},
            },
        ),
    ]
