# Generated by Django 3.2.4 on 2021-09-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_mystatus_info'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mystatus',
            unique_together={('user', 'year')},
        ),
    ]
