# Generated by Django 3.2.4 on 2021-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_alter_mystatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfreedays',
            name='day_str',
            field=models.CharField(max_length=25),
        ),
    ]
